### ISSUE TITLE
Can't find Meshchat LUA Package

### ISSUE THREAD

**Issue by rmcgee1** [hickey/meshchat#27]
I can see the various Meshchat LUA source code and libraries, but what I can't find is an installable package.
Am I missing that somewhere?

**Comment by rmcgee1** [comment]
I was able to find an installable 2.8 lua package on another site, so I've got Meshchat working. However, since all the major links point to this repository now, I wanted you to be aware of that.

**Comment by gerner** [comment]
we're working on the next release of meshchat, it's not out yet.

**Comment by james-coder** [comment]
> we're working on the next release of meshchat, it's not out yet.

Does this mean I should use the .ipk from here for now? https://github.com/kn6plv/meshchat (2.10)
I also found it confusing because the repo above pointed to this repo. It seems you have some GitHub Actions, but no releases.

**Comment by hickey** [comment]
Sorry, I just realized that this issue got created without the `needs triage` label and that is how I find issues that need to be responded to. Maybe this issue was created before I had the issue templates in place? 

You found the last release that KN6PLV released. I am literally  in the final minutes before the next production release. That is how I found your issue as I was pruning the issues to insure everything got addressed for the release. By the time you read this you should find the v2.12.0 release.
