### ISSUE TITLE
[Feature]: Docker Release

### ISSUE THREAD

**Issue by JPurp** [hickey/meshchat#55]
### Enhancement Type

Installation method

### What is your idea or what can be improved?

Offer a docker image. This will allow AREDN sites that are using docker to add services a way to quickly and easily add MeshChat. By running this via docker on dedicated hardware (x86/ARM) it takes load off of the AREDN node, especially nodes with limited RAM.

**Comment by hickey** [comment]
Unfortunately, it is not quite that simple. Actually I should not say that, it is that simple, but the code needs to be ported to Linux first. Either that or one needs to build a Docker image with the OpenWRT distribution in it and then layer on top MeshChat. I suspect that would be a bunch more work than just getting MeshChat ported over to run on Linux. 

Actually that work (porting to Linux) is mostly done and is trying to be completed so that a new release can be produced. With luck we will start to see a release at the end of the year or shortly afterward.

**Comment by lcd15000** [comment]
This issue is marked as completed, does this mean that Docker is not on the roadmap? I too would like see a docker release to shift system load off of my node. In the last response on this issue it seems that https://github.com/hickey/meshchat/issues/6 is a blocker? Would it be feasible to re-open this issue once https://github.com/hickey/meshchat/issues/6 is resolved?
