### ISSUE TITLE
[Bug]: MeshChat Fails with AREDN Releases after 3.24.10.0

### ISSUE THREAD

**Issue by K5RA** [hickey/meshchat#56]
### Contact Details

k5ra@verizon.net

### Version

v1.x

### System Type

Linux

### What happened?

I have MeshChat 1.02 running in my R-pi and Meschat _api_2.12 in my hAP ac lite.  When I upgraded to AREDN NB 20241202 almost a week ago, my MeshChat instance stopped syncing with the other two other servers  on our mesh island.  One instance is still at 3.24.10.0, the other is an NB20241208.  When I reverted to 3.24.10.0, my MeshChat began to sync with the other node on the stable release, but there are still issues..  

### MeshChat configuration

```
<Insert config file here>
```

### Connection type

None

### What browsers are you seeing the problem on?

Chrome

**Comment by la9ky** [comment]
Hi

copied from my post in the Aredn forum;

I am on Night build version on hAP ac lite and also Nanobeam,
I have tried to get Meshchat to work since I had to leave latest release for the bug in vlan tagging / DtD.
I have installed Meschat 2.12.1 and I get the login and the message window.
The syslog gets flooded with 
Wed Dec 11 20:53:47 2024 daemon.err uhttpd[1491]: /usr/bin/lua: /www/cgi-bin/meshchat:52: attempt to call field 'Request' (a nil value)
Wed Dec 11 20:53:48 2024 daemon.err uhttpd[1491]: /usr/bin/lua: /www/cgi-bin/meshchat:52: attempt to call field 'Request' (a nil value)
Wed Dec 11 20:53:58 2024 daemon.err uhttpd[1491]: /usr/bin/lua: /www/cgi-bin/meshchat:52: attempt to call field 'Request' (a nil value)
Wed Dec 11 20:53:58 2024 daemon.err uhttpd[1491]: /usr/bin/lua: /www/cgi-bin/meshchat:52: attempt to call field 'Request' (a nil value)
Wed Dec 11 20:53:58 2024 daemon.err uhttpd[1491]: /usr/bin/lua: /www/cgi-bin/meshchat:52: attempt to call field 'Request' (a nil value)
 
and  I see a file /meshchat/messages.MeshChat-6349 that probably should have been written over when I set up the service with Meshchat-LA9KY (ex)

To quote Keb Mo's song; Am I wrong?
Any ideas of how to make Meshchat work again would be great :-)

Frank

**Comment by K5RA** [comment]
Frank -
I use a hap ac lite and a RPi 5B.  The hap had 3.24.10.0 and MeshChat-api-2.12.1, and the Pi had MeshChat 1.02_all.deb.  There were three MeshChat servers on our zone in that configuration.  One of them upgraded to a nightly build (NB) around 16 Oct.  That server would not sync with the other servers.  Since we had two good servers, we just let it go.   I upgraded my hAP to NB1202, and that knocked out my MeshChat.  I worked problem for several days, and finally found a fix.  I let it go for several days, then upgraded to NB1212 this morning.  That killed my MeshChat again.  It would not sync with the one good server, or with a second good server that came up later.
I worked over three hours this morning, trying various combinations of rebooting the hAP and the R-Pi, deleting and re-installing the meshchat API and the service announcement in the hAP, reinstalling (overwriting) meshchat in the R-Pi, reinstalling 3.24.10.0 in the hAP, .....  Nothing worked.
I finally did what was successful a couple days ago.  
1. In your hAP, delete the MeshChat service announcement and remove the meshchat api package.  Reboot the hAP.
2. If your hAP has the NB firmware, take it back to 3.24.10.0.  Confirm that the API is not in the system, and that there is no meshchat service announcement. Reboot the hAP.
3. Take your hAP back to 3.24.6.0 firmware.  This release has the old UI.  The auto-browsing from 3.24.10.0 will not work.  After about ten minutes, browse to localnode.local.mesh:8080/cgi-bin/status or something like that.  Log in to Setup page.  On Services page, confirm that Meshchat Service is not advertised..  On Admin page, upgrade your firmware to 3.24.10.0.  
4. When node recovers, it will come up with Old UI. Confirm that you have 3.24.10.0.  Switch to new UI.   Install the meshchat-api-2.12.1.ipk package.    Configure your Local Services Meshchat announcement.  Commit change.  Reboot the hAP.  
5. When node recovers (about 8 minutes after reboot start), check your Local Service announcement.s.  Meshchat should not have the "Service cannot be found" icon (triangle with dot in it).  Open your and other MeshChat services on your mesh island, and determine that your service has synchronized with them (identical messages shown). 

I know there is no logic to this, but it has worked for me twice.  

I believe that old  messages.svcname  files are not overwritten.  They just go inactive when you change your Meshchat zone name.  I have five of them in an OldFiles directory.  

I feel I have proved that there is an issue with Meshchat and recent NBs.  Right now, to have MeshChat, we appear to need to be on 3.24.10.0.  Unnskyld.  

Lukke til! 

--Tim K5RA

**Comment by la9ky** [comment]
Tim,
Thank you, unfortunately I will only be able to try this on saturday, but
very detailed guidline so I will do.

 Takk Tim :-)

tor. 12. des. 2024 kl. 22:01 skrev Tim Bratton ***@***.***>:

**Comment by K5RA** [comment]
This afternoon, the remaining MeshChat server on our mesh island that had dysfunctioning Meshchat was healed using the procedure above.  We do not know why, but it has worked for me twice and for another station once.  

If you need MeshChat and do not need firmware past 3.24.10.0, this may be a fix.

**Comment by hickey** [comment]
Tim, 

Unfortunately, MeshChat `1.02` is extremely old and it not supported any longer. The more unfortunate thing is that it is the only version that runs on Linux. 

I do believe the problem that you are running into is that the newer versions of AREDN firmware are now putting service metadata (icons to show what type of service it is) into the service name and that is causing `meshchatsync` to see the service announcement for the MeshChat group to be another MeshChat group entirely. I had to produce a hotfix release to patch the `v2.x` versions when the firmware started to include the metadata. 

There is no one maintaining the `1.02` code base so it is not going to get fixed. What you may be able to do is to look at the actual service name and use that value in your MeshChat config file. With luck that will keep you running until I finalize the Linux build of the `v2.x` code base. 

Looking at https://github.com/hickey/meshchat/pull/52/files, this was the change for selecting the correct service name. I don't have specific info on what the new format is, but I think that the service name now has the icon info surrounded by pipe characters (`|`).

**Comment by hickey** [comment]
The other option that can be done is to turn off the icon on the services for MeshChat. This has to be done on all the nodes advertising a MeshChat service. All the other services are fine with setting icons--it is just the MeshChat service that has to have the icon removed. At least until all MeshChats has been upgraded to `v2.12.1` or later.

**Comment by hickey** [comment]
Frank, 

The issue that you are describing is not related and should be opened as a new issue. Please do that and reference the node name that is experiencing this issue so that I can look at that node and see if I notice anything that is off. 

Thanks.

**Comment by K5RA** [comment]
Gerard -
Thank you for the detailed answers.  The R-Pi does not like the .ipk versions of new MeshChat.  Says can not install because not Debian format. 
As we have grown beyond our NanoStations and similar low-storage devices, we could run MeshChat in our hAP nodes.  The total size of the message.NEW-NTXChat database file in my node is about 140KB for about 2.5 months of traffic.  The /meshchat archive is huge because it is stored so inefficiently (one message per disk sector?). 
I have seen the discussion of service type icons being appended to Local Service names.  Had not made the connection, but maybe that is a NB thing.  I will try again with no service icon.  Not ideal, but there are a lot of folks who need MeshChat and fixes in the nightly builds. We are all running API 2.12.1, and we can remove the icons to see if that makes a difference.  OR if we all had exactly the same set of icons, would be be OK???
Thanks. 
--Tim K5RA

**Comment by hickey** [comment]
Correct, the `ipk` format is not a Debian package format. It is used by OpenWRT and a few other embedded Linux environments. The next version of MeshChat will be able to be installed on Linux and you will see `deb` files for installing on Debian and Ubuntu. 

As for your question about all the services using the same icon that will not work, unfortunately. The problem is that the icon metadata is being added to the service name and that causes `meshchatsync` to not see the correct service name. That is why I was thinking that maybe adding the icon metadata to the MeshChat service name in the config file may possibly be a short term work around until the `v2.x` code is available for Linux.

**Comment by K5RA** [comment]
Would this be the the   $pi_zone parameter in the meshchatconfig.pm file??    I can set up two AREDN nodes and run an experiment.  NEW-NTXChat[chat]?
